<?php
require 'index.php';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-04 at 09:43:08.
 */
class TestPHPTest extends PHPUnit_Framework_TestCase {

    /**
     * @var TestPHP
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new TestPHP;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert (2, 1) == 3.
     *
     * @covers TestPHP::add
     */
    public function testAdd() {
        $this->assertEquals(
                3, $this->object->add(2, 1)
        );
    }

    /**
     * Generated from @assert (1, 1) == 2.
     *
     * @covers TestPHP::add
     */
    public function testAdd2() {
        $this->assertEquals(
                2, $this->object->add(1, 1)
        );
    }

    /**
     * Generated from @assert (5, 5) == 10.
     *
     * @covers TestPHP::add
     */
    public function testAdd3() {
        $this->assertEquals(
                10, $this->object->add(5, 5)
        );
    }


}

